[DIA-1178] `meta-data` GET request and unit tests implemented
SourcePointUSA/ios-cmp-app pull request #383
Opened 2022-09-11 19:35 UTC by Nevazhnovu

2022-09-12 08:24 UTC, andresilveirah requested changes

2022-09-12 08:24 UTC, andresilveirah commented on ConsentViewController/Classes/SPError.swift
> +@objcMembers public class InvalidMetaDataQueryResponseError: SPError {
I believe the correct name should be `InvalidMetaDataResponseError` (there's no _query_ in the response).

2022-09-12 08:24 UTC, andresilveirah commented on ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift
> +        metadata: ConsentStatusMetaData
@Nevazhnovu the `metadata` of the `/meta-data` request is different from the `metadata` from the `/consent-status` request :D 

I believe you'll need to implement another struct to encapsulate it. Its attributes should be:
```
{
    ccpa?: {
        hasLocalData: boolean
        dateCreated?: string
        uuid?: string
    },
    gdpr?: {
        hasLocalData: boolean
        dateCreated?: string
        uuid?: string
    }
}
```
You can base your new struct on the `ConsentStatusMetaData`.

2022-09-12 08:26 UTC, andresilveirah commented
@Nevazhnovu once you address the comments above and add its specs to `UnmockedSourcepointClientSpec` we should be good to go.

2022-09-12 08:30 UTC, carmelo-iriti commented
do you usually create tests in a different MR?

2022-09-12 08:35 UTC, andresilveirah commented
> do you usually create tests in a different MR?

@carmelo-iriti no. I think tests are part of the feature/bug fix.

2022-09-16 10:20 UTC, Nevazhnovu commented
@andresilveirah code review fixes are pushed, pls review!

2022-09-16 10:51 UTC, andresilveirah approved these changes

2022-09-16 12:39 UTC, merged